# permissions for end users to edit machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: machine-editor-role
rules:
- apiGroups:
  - cluster.x-k8s.io.mydomain.com
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io.mydomain.com
  resources:
  - machines/status
  verbs:
  - get
