apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: workload-cluster
    nodepool: nodepool-0
  name: slurm-head
  namespace: metal3
spec:
  clusterName: workload-cluster
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: workload-cluster
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: workload-cluster
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: VirtualKubeletConfigTemplate
          name: virtualkubeletconfigtemplate-head
      clusterName: workload-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        name: workload-clustervirtkube-node
      nodeDrainTimeout: 0s
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: workload-clustervirtkube-node
  namespace: metal3
spec:
  template:
    spec:
      dataTemplate:
        name: workload-clustervirtkube-node-template
      image:
        checksum: http://172.22.0.1/images/CentOS-raw.img.sha256sum 
        checksumType: sha256
        format: raw
        url: http://172.22.0.1/images/CentOS-raw.img
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: workload-clustervirtkube-node-template
  namespace: metal3
spec:
  clusterName: workload-cluster
  metaData:
    ipAddressesFromIPPool:
    - key: provisioningIP
      name: provisioning-pool
    objectNames:
    - key: name
      object: machine
    - key: local_hostname
      object: machine
    - key: name_m3m
      object: metal3machine
    - key: name_bmh
      object: baremetalhost
    ipAddressesFromIPPool:
    - key: ip
      name: externalv4-pool
    prefixesFromIPPool:
    - key: mask
      name: externalv4-pool
    gatewaysFromIPPool:
    - key: gateway
      name: provisioning-pool
    dnsServersFromIPPool:
    - key: dns
      name: provisioning-pool
    fromHostInterfaces:
    - key: mac1
      interface: "enp1s0"
    fromHostInterfaces:
    - key: mac2
      interface: "enp2s0"
    fromLabels:
    - key: label-1
      object: machine
      label: mylabelkey
  networkData:
    links:
      ethernets:
      - id: enp1s0
        macAddress:
          fromHostInterface: enp1s0
        type: phy
      - id: enp2s0
        macAddress:
          fromHostInterface: enp2s0
        type: phy
    networks:
      ipv4:
      - id: externalv4
        ipAddressFromIPPool: externalv4-pool
        link: enp2s0
        routes:
        - gateway:
            fromIPPool: externalv4-pool
          network: 0.0.0.0
          prefix: 0
    services:
      dns:
      - 8.8.8.8
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: VirtualKubeletConfigTemplate
metadata:
  labels:
    app.kubernetes.io/name: virtualkubeletconfigtemplate
    app.kubernetes.io/instance: virtualkubeletconfigtemplate-head
    app.kubernetes.io/part-of: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-bootstrap-virtual-kubelet
  name: virtualkubeletconfigtemplate-head
  namespace: metal3
spec:
  template:
    spec:
      format: cloud-config
      files:
        - content: |
            # slurm.conf file generated by configurator.html.
            # Put this file on all nodes of your cluster.
            # See the slurm.conf man page for more information.
            #
            ClusterName=my-first-cluster
            SlurmctldHost={{ ds.meta_data.name_bmh }}
            MpiDefault=none
            ProctrackType=proctrack/linuxproc
            ReturnToService=2
            SlurmctldPidFile=/var/run/slurmctld.pid
            SlurmctldPort=6817
            SlurmdPidFile=/var/run/slurmd.pid
            SlurmdPort=6818
            SlurmdSpoolDir=/var/lib/slurm/slurmd
            SlurmUser=slurm
            StateSaveLocation=/var/lib/slurm/slurmctld
            SwitchType=switch/none
            TaskPlugin=task/none
            #
            # DYNAMIC NODES
            TreeWidth=65533 # To disable fanout
            MaxNodeCount=12 
            #
            # TIMERS
            InactiveLimit=0
            KillWait=30
            MinJobAge=300
            SlurmctldTimeout=120
            SlurmdTimeout=300
            Waittime=0
            # SCHEDULING
            SchedulerType=sched/backfill
            SelectType=select/cons_tres
            SelectTypeParameters=CR_Core
            #
            #AccountingStoragePort=
            AccountingStorageType=accounting_storage/none
            JobCompType=jobcomp/none
            JobAcctGatherFrequency=30
            JobAcctGatherType=jobacct_gather/none
            SlurmctldDebug=info
            SlurmctldLogFile=/var/log/slurm/slurmctld.log
            SlurmdDebug=info
            SlurmdLogFile=/var/log/slurm/slurmd.log
            #
            # COMPUTE NODES
            NodeSet=my-worker-nodes Feature=my-worker

            PartitionName=default-partition Nodes=ALL Default=YES MaxTime=INFINITE State=UP
            PartitionName=my-first-cluster-partition Nodes=my-worker-nodes MaxTime=INFINITE State=UP
          path: /etc/slurm/slurm.conf
          permissions: '0644'
        - content: |
            #!/bin/sh
            export MUNGEUSER=1011
            sudo groupadd -g $MUNGEUSER munge
            sudo useradd  -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge  -s /sbin/nologin munge
            export SLURMUSER=1012
            sudo groupadd -g $SLURMUSER slurm
            sudo useradd  -m -c "SLURM workload manager" -d /var/lib/slurm -u $SLURMUSER -g slurm  -s /bin/bash slurm
            sudo dnf -y install munge munge-libs 
            sudo chmod 400 /etc/munge/munge.key
            sudo chown munge:munge /etc/munge/munge.key
            sudo systemctl start munge

            yum install epel-release -y
            sudo yum -y install slurm-slurmd slurm-slurmctld
            sudo systemctl start slurmctld

            sudo systemctl enable munge
            sudo systemctl enable slurmctld
          path: /tmp/setup_slurm_head.sh
          permissions: '0744'
        - content: |
            dOXElHimTjBV158GJRVejlx8cgunw7KPpQVPJKqGA4R2OXM57ANsNHxWKzibMKocaK53N1J2y18x
            Xq1lBFmedlxiP3B6RCeZ+cFuXFSpC5wRG+EyK2cRcrlcqLUQBiHM9GiZbJd+1WN1yCX7FwVM77lU
            jPZf6gwVwaC0cB5vUY6zyFP3qG2OpGZCjpUAeat2N12kLcfGC7ebZ5Rg8o3Ma3q/TXf46q0qdSDd
            R+LHKMG88iBaXvboqqljga4Yq9lr+LBVcMaOQ2J/2SP1xDHIWfizATAT1gJA6EC9ljLIBbM+d34/
            FlDOPOX6xQQXQbiYjSfjrd+LuLqTx6+fTY1y1rEv5xpXsjsRi4dEX7vTKvhsNSWUxIxq0DrQED05
            UipvHYE/tIPHRvoSenn8CSEQaF6QOLOtDn4h8Wkt7iGIyhsGi3mU6D/0/gwac7yRjXpXjrAq2p2q
            9MDsGcJrFe2UECVRrRCezbYYhTD3i1bqv2iH2esqoUhaTnDhHJyVr2+DBtdvjjGDrwELsiiJFWuS
            lysJWLCHZ8fkd3/oZh3jgq1MCeth4AVe80ZeoF3NZdoQLcwviiRLLYLf7xhizwrxVC02NAjYIISO
            YNjD8eDT9hfZGJoeg0vLzdkaJFsuvqfHEdLET8maqicBPL5r38mYABkRGWLCqx31nzP2avQjSEO6
            zCqqg9ZH3+RsC7+VZ29+Jn/bXUSZol0gAmrfIpivHO6m+XURUWG9O4dHqG6oOkQ2YNYo5TDrWbF4
            I2Q89U6aHV7lHzq7KBxMiVb2ctnfHIgAP8VnVPrsXgTY2EjubICdTD1UE+AalJm2TZEDx5nlISzz
            ctCWcoBkoj8lf+oHn/S+IfpHITY+8vBLdnB7DbAkMzUrBZ5gyYerUTfaZoRFb1tyBfWjJSbqKjgz
            jomUootjQ1temkz1wxcJ9BqCnjJvLFN56FIRuAaQNrFdbexCCUc3wZwO49ASaNU16oy6sAvMQTWv
            VppP/Z+scFinPwOeROeD+jDoqwyfG7TfKiLFQdTxlpah88zGO+Id8AnNswfSKFKbJLlTNouUzyYO
            mWbB/+aTZCRO9t2vxS0UC4x6h9IR9WTfvY+ezORsIgZYxtz1krCO5W+DjJGLFf9m/AMluhqCJf2w
            BZAbrxoRum67ub1QtQpS51zR88wp+Ogr5vpGOp3CA66KSYiEK6B8lQah9Yt2/5Vb3V9YIG6+7we1
            JQ0qMYB40Hap1NWFLo8NIY9Yb1Wvd3ifkGz4qsrVjv2lLkaoGPeJLb+/78PU8ZtKpi3Ux3RxTwev
            0AY9fjYg4Tmk6tC5hqN+Y3iYmWTCKlywFMhO/i7gnYhJqaUOv/gB5dogQv+3jylbfwnEV0VXxQ==
          path: /tmp/munge.key
          permissions: '0744'
        - content: |
            #!/bin/sh
            sudo yum install mpich mpich-devel -y
            . /etc/profile
            module load mpi
            sudo yum install nfs-utils -y
            mkdir /home/mik/slurm_tests
            sudo chmod 777 /home/mik/slurm_tests
            sudo systemctl start rpcbind
            sudo systemctl start nfs-server
            echo "/home/mik/slurm_tests   192.168.111.248/24(rw,sync,no_root_squash)" | sudo tee -a /etc/exports
            sudo systemctl restart nfs-server
          path: /tmp/setup-mpich-nfs-head.sh
          permissions: '0744'
        - path: /etc/keepalived/keepalived.conf
          content: |
            ! Configuration File for keepalived
            
            vrrp_instance VI_2 {
              state MASTER
              interface eth1
              virtual_router_id 2
              priority 255
              advert_int 1
              virtual_ipaddress {
                    192.168.111.248/24
              }
            }
        - content: |
            #include <mpi.h>
            #include <stdio.h>
            #include <unistd.h> // Include for gethostname
            #include <limits.h> // Include for HOST_NAME_MAX

            int main(int argc, char *argv[])
            {
                int rank, size;
                char hostname[HOST_NAME_MAX];

                MPI_Init(&argc, &argv);

                MPI_Comm_rank(MPI_COMM_WORLD, &rank);
                MPI_Comm_size(MPI_COMM_WORLD, &size);

                gethostname(hostname, sizeof(hostname));

                printf("Hello, World. I am rank %d of %d on host %s\n", rank, size, hostname);

                MPI_Finalize();
                return 0;
            }
          path: /home/mik/slurm_tests/mpi-hello-world.c
          permissions: '0744'
        - content: |
            module load mpi
            mpicc mpi-hello-world.c -o mpi-hello-world
            sudo srun -N 6 --mpi=pmi2 mpi-hello-world
          path: /home/mik/slurm_tests/hello-world.sh
          permissions: '0747'
      users:
        - name: mik
          sudo: ALL=(ALL) NOPASSWD:ALL
      commands:
        - sudo mkdir -p /etc/munge/
        - cat /tmp/munge.key | base64 -d | sudo tee -a /etc/munge/munge.key
        - ./tmp/setup_slurm_head.sh 
        - ./tmp/setup-mpich-nfs-head.sh
        - sudo systemctl start keepalived
