apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name:  workload-cluster
    nodepool: nodepool-0
  name: slurm-worker
  namespace: metal3
spec:
  clusterName:  workload-cluster
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name:  workload-cluster
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name:  workload-cluster
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: VirtualKubeletConfigTemplate
          name: virtualkubeletconfigtemplate-worker
      clusterName:  workload-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        name:  workload-clustervirtkube-node
      nodeDrainTimeout: 0s
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: VirtualKubeletConfigTemplate
metadata:
  labels:
    app.kubernetes.io/name: virtualkubeletconfigtemplate
    app.kubernetes.io/instance: virtualkubeletconfigtemplate-worker
    app.kubernetes.io/part-of: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-bootstrap-virtual-kubelet
  name: virtualkubeletconfigtemplate-worker
  namespace: metal3
spec:
  template:
    spec:
      format: cloud-config
      files:
        - content: |
            # slurm.conf file generated by configurator.html.
            # Put this file on all nodes of your cluster.
            # See the slurm.conf man page for more information.
            #
            ClusterName=my-first-cluster
            SlurmctldHost=192.168.111.248
            MpiDefault=none
            ProctrackType=proctrack/linuxproc
            ReturnToService=2
            SlurmctldPidFile=/var/run/slurmctld.pid
            SlurmctldPort=6817
            SlurmdPidFile=/var/run/slurmd.pid
            SlurmdPort=6818
            SlurmdSpoolDir=/var/lib/slurm/slurmd
            SlurmUser=slurm
            StateSaveLocation=/var/lib/slurm/slurmctld
            SwitchType=switch/none
            TaskPlugin=task/none
            #
            # DYNAMIC NODES
            TreeWidth=65533 # To disable fanout
            MaxNodeCount=12 
            #
            # TIMERS
            InactiveLimit=0
            KillWait=30
            MinJobAge=300
            SlurmctldTimeout=120
            SlurmdTimeout=300
            Waittime=0
            # SCHEDULING
            SchedulerType=sched/backfill
            SelectType=select/cons_tres
            SelectTypeParameters=CR_Core
            #
            #AccountingStoragePort=
            AccountingStorageType=accounting_storage/none
            JobCompType=jobcomp/none
            JobAcctGatherFrequency=30
            JobAcctGatherType=jobacct_gather/none
            SlurmctldDebug=info
            SlurmctldLogFile=/var/log/slurm/slurmctld.log
            SlurmdDebug=info
            SlurmdLogFile=/var/log/slurm/slurmd.log
            #
            # COMPUTE NODES
            NodeSet=my-worker-nodes Feature=my-worker

            PartitionName=default-partition Nodes=ALL Default=YES MaxTime=INFINITE State=UP
            PartitionName=my-first-cluster-partition Nodes=my-worker-nodes MaxTime=INFINITE State=UP
          path: /etc/slurm/slurm.conf
          permissions: '0644'
        - content: |
            #!/bin/sh
            export MUNGEUSER=1011
            sudo groupadd -g $MUNGEUSER munge
            sudo useradd  -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge  -s /sbin/nologin munge
            export SLURMUSER=1012
            sudo groupadd -g $SLURMUSER slurm
            sudo useradd  -m -c "SLURM workload manager" -d /var/lib/slurm -u $SLURMUSER -g slurm  -s /bin/bash slurm
            sudo dnf -y install munge munge-libs 
            sudo chmod 400 /etc/munge/munge.key
            sudo chown munge:munge /etc/munge/munge.key
            sudo systemctl start munge

            yum install epel-release -y
            sudo yum -y install slurm-slurmd
            sudo systemctl start slurmd

            sudo systemctl enable munge
            sudo systemctl enable slurmd
          path: /tmp/setup_slurm_compute.sh
          permissions: '0744'     
        - content: |
            dOXElHimTjBV158GJRVejlx8cgunw7KPpQVPJKqGA4R2OXM57ANsNHxWKzibMKocaK53N1J2y18x
            Xq1lBFmedlxiP3B6RCeZ+cFuXFSpC5wRG+EyK2cRcrlcqLUQBiHM9GiZbJd+1WN1yCX7FwVM77lU
            jPZf6gwVwaC0cB5vUY6zyFP3qG2OpGZCjpUAeat2N12kLcfGC7ebZ5Rg8o3Ma3q/TXf46q0qdSDd
            R+LHKMG88iBaXvboqqljga4Yq9lr+LBVcMaOQ2J/2SP1xDHIWfizATAT1gJA6EC9ljLIBbM+d34/
            FlDOPOX6xQQXQbiYjSfjrd+LuLqTx6+fTY1y1rEv5xpXsjsRi4dEX7vTKvhsNSWUxIxq0DrQED05
            UipvHYE/tIPHRvoSenn8CSEQaF6QOLOtDn4h8Wkt7iGIyhsGi3mU6D/0/gwac7yRjXpXjrAq2p2q
            9MDsGcJrFe2UECVRrRCezbYYhTD3i1bqv2iH2esqoUhaTnDhHJyVr2+DBtdvjjGDrwELsiiJFWuS
            lysJWLCHZ8fkd3/oZh3jgq1MCeth4AVe80ZeoF3NZdoQLcwviiRLLYLf7xhizwrxVC02NAjYIISO
            YNjD8eDT9hfZGJoeg0vLzdkaJFsuvqfHEdLET8maqicBPL5r38mYABkRGWLCqx31nzP2avQjSEO6
            zCqqg9ZH3+RsC7+VZ29+Jn/bXUSZol0gAmrfIpivHO6m+XURUWG9O4dHqG6oOkQ2YNYo5TDrWbF4
            I2Q89U6aHV7lHzq7KBxMiVb2ctnfHIgAP8VnVPrsXgTY2EjubICdTD1UE+AalJm2TZEDx5nlISzz
            ctCWcoBkoj8lf+oHn/S+IfpHITY+8vBLdnB7DbAkMzUrBZ5gyYerUTfaZoRFb1tyBfWjJSbqKjgz
            jomUootjQ1temkz1wxcJ9BqCnjJvLFN56FIRuAaQNrFdbexCCUc3wZwO49ASaNU16oy6sAvMQTWv
            VppP/Z+scFinPwOeROeD+jDoqwyfG7TfKiLFQdTxlpah88zGO+Id8AnNswfSKFKbJLlTNouUzyYO
            mWbB/+aTZCRO9t2vxS0UC4x6h9IR9WTfvY+ezORsIgZYxtz1krCO5W+DjJGLFf9m/AMluhqCJf2w
            BZAbrxoRum67ub1QtQpS51zR88wp+Ogr5vpGOp3CA66KSYiEK6B8lQah9Yt2/5Vb3V9YIG6+7we1
            JQ0qMYB40Hap1NWFLo8NIY9Yb1Wvd3ifkGz4qsrVjv2lLkaoGPeJLb+/78PU8ZtKpi3Ux3RxTwev
            0AY9fjYg4Tmk6tC5hqN+Y3iYmWTCKlywFMhO/i7gnYhJqaUOv/gB5dogQv+3jylbfwnEV0VXxQ==
          path: /tmp/munge.key
          permissions: '0744'
        - content: |
            #!/bin/sh

            sudo yum install mpich mpich-devel -y
            . /etc/profile
            module load mpi
            sudo yum install nfs-utils -y
            mkdir -p /home/mik/slurm_tests
            sudo chmod 777 /home/mik/slurm_tests
            sudo mount -t nfs 192.168.111.248:/home/mik/slurm_tests /home/mik/slurm_tests
          path: /tmp/setup_mpich_nfs.sh
          permissions: '0744'   
        - content: !!binary |
            Ly8gSXQgd2lsbCBiZSBzdGFydGVkIGJ5IHRoZSB2aXJ0dWFsa3ViZWxldCBpbnNpZGUgdGhlIG5v
            ZGUKcGFja2FnZSBtYWluCgppbXBvcnQgKAoJImZtdCIKCSJuZXQvaHR0cCIKCSJvcy9leGVjIgoJ
            InJlZ2V4cCIKCSJzdHJpbmdzIgoJInRpbWUiCikKCmZ1bmMgaGVsbG8odyBodHRwLlJlc3BvbnNl
            V3JpdGVyLCByZXEgKmh0dHAuUmVxdWVzdCkgewoJZm10LkZwcmludGYodywgImhlbGxvXG4iKQp9
            CgpmdW5jIGdldEhvc3RuYW1lKCkgc3RyaW5nIHsKCWNtZCA6PSBleGVjLkNvbW1hbmQoImhvc3Ru
            YW1lIikKCXN0ZG91dCwgXyA6PSBjbWQuT3V0cHV0KCkKCWhvc3RuYW1lIDo9IHN0cmluZ3MuVHJp
            bVN1ZmZpeChzdHJpbmcoc3Rkb3V0KSwgIlxuIikKCWZtdC5QcmludGYoIkRldGFjdGluZyAlcyBm
            cm9tIHNsdXJtIGNsdXN0ZXJcbiIsIGhvc3RuYW1lKQoJcmV0dXJuIGhvc3RuYW1lCn0KCmZ1bmMg
            ZGVsZXRlTm9kZUZyb21DbHVzdGVyKGhvc3RuYW1lIHN0cmluZykgewoJY21kIDo9IGV4ZWMuQ29t
            bWFuZCgic3VkbyIsICJzY29udHJvbCIsICJkZWxldGUiLCAibm9kZW5hbWUiLCBob3N0bmFtZSkK
            CXN0ZG91dCwgZXJyIDo9IGNtZC5PdXRwdXQoKQoJaWYgZXJyICE9IG5pbCB7CgkJZm10LlByaW50
            KHN0cmluZyhzdGRvdXQpKQoJCWZtdC5QcmludGxuKCJDYW5ub3QgZGV0YWNoOiAiICsgZXJyLkVy
            cm9yKCkpCgkJcmV0dXJuCgl9CglmbXQuUHJpbnRsbihzdHJpbmcoc3Rkb3V0KSkKCWZtdC5Qcmlu
            dGxuKCJEZXRhY2hlZCBmcm9tIFNsdXJtIikKfQoKZnVuYyBkZXRhY2hGcm9tU2x1cm1jbHVzdGVy
            KHcgaHR0cC5SZXNwb25zZVdyaXRlciwgcmVxICpodHRwLlJlcXVlc3QpIHsKCWhvc3RuYW1lIDo9
            IGdldEhvc3RuYW1lKCkKCglmbXQuUHJpbnRsbigiRm9yY2luZyIpCgljbWQgOj0gZXhlYy5Db21t
            YW5kKCJzdWRvIiwgInNjb250cm9sIiwgInVwZGF0ZSIsICJOb2RlTmFtZT0iK2hvc3RuYW1lLCAi
            U3RhdGU9RE9XTiIsICJSZWFzb249ZGVwcm92aXNpb24iKQoJc3Rkb3V0LCBlcnIgOj0gY21kLk91
            dHB1dCgpCglpZiBlcnIgIT0gbmlsIHsKCQlmbXQuUHJpbnQoc3RyaW5nKHN0ZG91dCkpCgkJZm10
            LlByaW50bG4oIkNhbm5vdCBEcmFpbjogIiArIGVyci5FcnJvcigpKQoJCXJldHVybgoJfQoKCWRl
            bGV0ZU5vZGVGcm9tQ2x1c3Rlcihob3N0bmFtZSkKfQoKZnVuYyBkcmFpbkFuZERldGFjaEZyb21T
            bHVybWNsdXN0ZXIodyBodHRwLlJlc3BvbnNlV3JpdGVyLCByZXEgKmh0dHAuUmVxdWVzdCkgewoJ
            aG9zdG5hbWUgOj0gZ2V0SG9zdG5hbWUoKQoKCWZtdC5QcmludGxuKCJEcmFpbmluZyIpCgljbWQg
            Oj0gZXhlYy5Db21tYW5kKCJzdWRvIiwgInNjb250cm9sIiwgInVwZGF0ZSIsICJOb2RlTmFtZT0i
            K2hvc3RuYW1lLCAiU3RhdGU9RFJBSU4iLCAiUmVhc29uPWRlcHJvdmlzaW9uIikKCXN0ZG91dCwg
            ZXJyIDo9IGNtZC5PdXRwdXQoKQoJaWYgZXJyICE9IG5pbCB7CgkJZm10LlByaW50KHN0cmluZyhz
            dGRvdXQpKQoJCWZtdC5QcmludGxuKCJDYW5ub3QgRHJhaW46ICIgKyBlcnIuRXJyb3IoKSkKCQly
            ZXR1cm4KCX0KCglyZWdleCwgXyA6PSByZWdleHAuQ29tcGlsZSgiU3RhdGU9SURMRVxcK0RSQUlO
            IikKCWZvciB7CgkJY21kID0gZXhlYy5Db21tYW5kKCJiYXNoIiwgIi1jIiwgInN1ZG8gc2NvbnRy
            b2wgc2hvdyBub2RlICIraG9zdG5hbWUpCgkJc3Rkb3V0LCBlcnIgPSBjbWQuT3V0cHV0KCkKCQlp
            ZiBlcnIgIT0gbmlsIHsKCQkJZm10LlByaW50KHN0cmluZyhzdGRvdXQpKQoJCQlmbXQuUHJpbnRs
            bigiQ2Fubm90IGdldCBub2RlIHN0YXR1czogIiArIGVyci5FcnJvcigpKQoJCQlyZXR1cm4KCQl9
            CgkJZm10LlByaW50KHN0cmluZyhzdGRvdXQpKQoKCQltYXRjaCA6PSByZWdleC5NYXRjaChzdGRv
            dXQpCgkJaWYgbWF0Y2ggewoJCQlicmVhawoJCX0KCgkJZm10LlByaW50bG4oIk5vZGUgaXMgYnVz
            eSwgd2FpdGluZyIpCgkJdGltZS5TbGVlcCgxICogdGltZS5TZWNvbmQpCgl9CgoJZGVsZXRlTm9k
            ZUZyb21DbHVzdGVyKGhvc3RuYW1lKQp9CgpmdW5jIG1haW4oKSB7CglodHRwLkhhbmRsZUZ1bmMo
            Ii9oZWxsbyIsIGhlbGxvKQoJaHR0cC5IYW5kbGVGdW5jKCIvZGV0YWNoIiwgZGV0YWNoRnJvbVNs
            dXJtY2x1c3RlcikKCWh0dHAuSGFuZGxlRnVuYygiL2RyYWluIiwgZHJhaW5BbmREZXRhY2hGcm9t
            U2x1cm1jbHVzdGVyKQoJaHR0cC5MaXN0ZW5BbmRTZXJ2ZSgiOjgwOTAiLCBuaWwpCn0K
          path: /tmp/server.go
          permissions: '0777'
        - content: |`
            #!/bin/sh

            export HOME=/home/mik
            export GOCACHE=/home/mik/.cache/go-build
            go build -v -x -o /tmp/server /tmp/server.go
            ./tmp/server > /tmp/server.log 2>&1 &
          path: /tmp/setup_go_server.sh
          permissions: '0744'  
      users:
        - name: mik
          sudo: ALL=(ALL) NOPASSWD:ALL
      commands:
        - ./tmp/setup_go_server.sh
        - sudo mkdir -p /etc/munge/
        - cat /tmp/munge.key | base64 -d | sudo tee -a /etc/munge/munge.key
        - ./tmp/setup_slurm_compute.sh && sudo slurmd -Z --conf "ThreadsPerCore=2 Feature=my-worker"
        - ./tmp/setup_mpich_nfs.sh

